### PR TITLE
Add ability to refresh token manually

### PR DESCRIPTION
**Pull request by MAKARD**
# JIRA Ticket

N/A 

# Description

Added an ability manually refresh access token regardless of its lifetime. 

# Definition of Done Checklist:

- [ ] Acceptance criteria is met.
- [ ] All tasks listed in the user story have been completed.
- [ ] Coded to standards.
- [ ] Ensure backward compatibility.
- [ ] API reference docs is updated.
- [ ] Unit tests are written.
- [ ] Integration tests are written.
- [ ] e2e tests are written.
- [ ] Functional spec is written/updated.
- [ ] Example code snippets have been added.
- [ ] Change log updated.
- [ ] Documentation story is created and tracked.
- [ ] Tech debts and remaining tasks are tracked in separated ticket(s).

### CODE REVIEW

**Comment by jeyanthanperiyasamy** [comment]
we need add tests and might do a potential end to end testing

**Comment by MAKARD** [comment]
> we need add tests and might do a potential end to end testing

I would really appreciate if you could do that instead of me, ‘cause I’m not iOS developer really

**Comment by george-bafaloukas-forgerock** [comment]
Hi @MAKARD I think it is best if we close the PR and integrate the changes in a branch originated internally, so that we can sort the tests and the pipelines.
Thanks a lot for your effort and raising this PR. 
We will keep you updated on the next steps.

Kind regards,
George Bafaloukas

**Comment by george-bafaloukas-forgerock** [comment]
Closing due to duplicate:
https://github.com/ForgeRock/forgerock-ios-sdk/pull/220

**Pull request closed without merging**
