### PR TITLE
SDKS-910-Remove_deprecated_methods

### PR DESCRIPTION
**Pull request by george-bafaloukas-forgerock**
- Removed ServerConfig deprecated public initializer
- Deleting deprecated FRAuth.shared.next() (public func next<T>) method from FRAuth.swift
- Removed FRURLProtocol.validatedURLs from FRURLProtocol.swift
- Removed deprecated FRURLProtocolResponseEvaluationCallback and dependencies from Typealias.swift, FRURLProtocol.swift, TokenManagementPolicy.swift
- Removed public var value from SingleValueCallback. The var has been replaced by getValue and setValue methods

### CODE REVIEW

**Review by jhoongo — CHANGES_REQUESTED** [review]
In general, looks good. Few comments:

1.  In DeviceCollectorNodeTests.swift line#813, it looks like this particular test is still using the .value property of Callback. This was supposed to be removed, but I might have overlooked this when I was refactoring all the test codes. It would be nice if you could handle this as this would throw an exception for building test.
2. CHANGELOG.md, the deprecation notice would be better to go under Deprecated section, and it would be nice if we can just list interfaces that are completely removed.

**Review by spetrov — COMMENTED** [review]
I agree with James that the removed methods should be listed in the "Deprecated" section below. Other than that everything looks good to me!

**Comment by george-bafaloukas-forgerock** [comment]
Hey @spetrov & @jhoongo, please have another look, comments addressed. Apologies while I did run the FRAuth tests I did miss those cases.

**Review by jhoongo — APPROVED** [review]

**Comment by jhoongo** [comment]
Looks good to me

**Pull request merged**
