### PR TITLE
[SDKS-644] [iOS] FRUser.getUserInfo returns an error from token renewal

### PR DESCRIPTION
**Pull request by jhoongo**

### CODE REVIEW

**Review by rodrigoareis — APPROVED** [review]
Looks good to me

**Review by spetrov — APPROVED** [review]
Looks good to me!

**Review by rodrigoareis — APPROVED** [review]
Changes looks good to me

**Comment by spetrov** [comment]
Closing this PR. Actual PR is https://github.com/ForgeRock/forgerock-ios-sdk/pull/62.

**Pull request closed without merging**
